### PR TITLE
Cdr4631 refresh dev

### PR DESCRIPTION
**Pull request by venglisch**
Modified cdr_dev_data.py to preserve test documents.

### CODE REVIEW

**Review by bkline — COMMENTED** [review]
Did these changes get promoted to production? If not, I don't thing we want them in master yet, do we?

**Comment by venglisch** [comment]
I'm sorry, you're right!  The changes did not make it to production.  I thought the library is only used as part of the PullDevDocs/PushDevDocs Devtools directory but as a member of the lib directory the changes have to be part of a release.  I guess we need to move this to Newton.

**Comment by bkline** [comment]
Can this PR be closed?

**Comment by venglisch** [comment]
I finally looked at this and it turns out I did a booboo by not doing anything.  Not sure why and how but I must have forgotten to move the changes because they weren't part of Ohm. :-(
I will go ahead and push the changes to Pauling and then close out this PR.

**Comment by venglisch** [comment]
The changes have been added to pauling.  Those changed files won't be used on PROD, only on DEV or QA and the lower tiers already include the latest updates.

**Pull request closed without merging**
